import type { Metadata } from 'next';
import { ViewTransitions } from 'next-view-transitions';
import { ThemeProvider } from '../components/provider';
import { Header } from './ui/header';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';

// eslint-disable-next-line new-cap
const fontSans = FontSans({
  subsets: [ 'latin' ],
  variable: '--font-sans',
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang='zh-CN' suppressHydrationWarning suppressContentEditableWarning >
        <body
          className={cn(
            'min-h-screen bg-skin-fill font-sans antialiased ',
            fontSans.variable,
          )}
        >
          <ThemeProvider attribute='class' defaultTheme='light' disableTransitionOnChange>
            <Header></Header>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
